ci(NODE-5344): add alpha release automation (#3712)

diff --git a/.github/workflows/release-alpha.yml b/.github/workflows/release-alpha.yml
--- a/.github/workflows/release-alpha.yml
+++ b/.github/workflows/release-alpha.yml
@@ -4,25 +4,36 @@ on:
   workflow_dispatch:
     inputs:
       alphaVersion:
-        description: 'The semver version string. MUST end in -alpha.#'
+        description: 'Enter alpha version'
         required: true
         type: string
-      wetRun:
-        description: 'If true, will publish to npm'
-        required: true
-        type: boolean
 
 name: release-alpha
 
 jobs:
-  release-nightly:
+  release-alpha:
     runs-on: ubuntu-latest
+    permissions:
+      id-token: write
     steps:
-      - run: |
-          [[ "${{ inputs.alphaVersion }}" =~ '-alpha(\.(0|[1-9][0-9]+))?$' ]] || { echo "Invalid alphaVersion string" ; exit 1; }
-          [[ "${{ inputs.wetRun }}" == "true" || "${{ inputs.wetRun }}" == "false" ]] || { echo "boolean wetRun must be provided" ; exit 1; }
-        shell: bash
-      - run: |
-          echo "${{ inputs.alphaVersion }}"
-          echo "${{ inputs.wetRun }}"
-        shell: bash
+      - shell: bash
+        run: |
+          ALPHA_SEMVER_REGEXP="-alpha(\.(0|[1-9][0-9]+))?$"
+
+          if ! [[ "${{ inputs.alphaVersion }}" =~ $ALPHA_SEMVER_REGEXP ]]; then
+            echo "Invalid alphaVersion string"
+            exit 1
+          fi
+      - uses: actions/checkout@v3
+      # TODO: replace with setup
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 'lts/*'
+          cache: 'npm'
+          registry-url: 'https://registry.npmjs.org'
+      - run: npm install -g npm@latest
+      - run: npm clean-install
+      - run: npm version "${{ inputs.alphaVersion }}" --git-tag-version=false
+      - run: npm publish --provenance --tag=alpha
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
